CRUD/Controllers/CategoriaController.cs
using CRUD.Core;
using CRUD.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD.Controllers
{
    public class CategoriaController : BaseController
    {
        public void IndexViewBags()
        {
            List<Categoria> categorias = UnitOfWork.CategoriaDal.ObterTodos().ToList();

            ViewBag.Categorias = categorias;
        }

        public ActionResult Index()
        {
            IndexViewBags();

            return View();
        }

        [HttpPost]
        public ActionResult Index(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                UnitOfWork.CategoriaDal.Adicionar(categoria);
                UnitOfWork.CategoriaDal.Salvar();

                IndexViewBags();

                return View();
            }

            return View();
        }

        public ActionResult Alterar(int id)
        {
            Categoria categoriaBanco = UnitOfWork.CategoriaDal.Obter(x => x.Id == id).FirstOrDefault();

            if(categoriaBanco != null)
            {
                return View(categoriaBanco);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Alterar(Categoria categoriaAlterada)
        {
            if (ModelState.IsValid)
            {
                UnitOfWork.CategoriaDal.Atualizar(categoriaAlterada);
                UnitOfWork.CategoriaDal.Salvar();

                return RedirectToAction("Index");
            }

            return View(categoriaAlterada);
        }

        public ActionResult Excluir(int id)
        {
            Categoria categoriaBanco = UnitOfWork.CategoriaDal.Obter(x => x.Id == id).FirstOrDefault();

            if(categoriaBanco != null)
            {
                return View(categoriaBanco);
            }

            return View();
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ExcluirCategoria(int id)
        {
            UnitOfWork.CategoriaDal.Excluir(x => x.Id == id);
            UnitOfWork.CategoriaDal.Salvar();

            return RedirectToAction("Index");
        }
    }
}

CRUD/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CRUD/Controllers/ProdutoController.cs
using CRUD.Core;
using CRUD.Dal.Contexto;
using CRUD.Model;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD.Controllers
{
    public class ProdutoController : BaseController
    {
        public void SetCategoriesViewBag()
        {
            List<Categoria> listaCategorias = UnitOfWork.CategoriaDal.ObterTodos().ToList();

            List<SelectListItem> categorias = new List<SelectListItem>();
            foreach(var item in listaCategorias)
            {
                categorias.Add(new SelectListItem { Text = item.Descricao, Value = item.Id.ToString() });
            }

            ViewBag.Categorias = categorias;
        }

        public void SetProductsViewBags()
        {
            List<Produto> produtos = UnitOfWork.ProdutoDal.ObterTodos().ToList();

            ViewBag.Produtos = produtos;
        }

        public ActionResult Index()
        {
            SetCategoriesViewBag();
            SetProductsViewBags();

            return View();
        }

        [HttpPost]
        public ActionResult Index(Produto produto)
        {
            if (ModelState.IsValid)
            {
                using(var transaction = new Entities().Database.BeginTransaction())
                {
                    try
                    {
                        UnitOfWork.ProdutoDal.Adicionar(produto);
                        UnitOfWork.ProdutoDal.Salvar();
                        
                        transaction.Commit();
                    }
                    catch (DbEntityValidationException ex)
                    {
                        transaction.Rollback();
                        throw;
                    }
                    catch (Exception)
                    {
                        transaction.Rollback();
                        throw;
                    }
                }

                SetCategoriesViewBag();
                SetProductsViewBags();

                return View();
            }

            return View(produto);
        }

        public ActionResult Alterar(int id)
        {
            SetCategoriesViewBag();

            Produto produtoBanco = UnitOfWork.ProdutoDal.Obter(x => x.Id == id).FirstOrDefault();

            if(produtoBanco != null)
            {
                return View(produtoBanco);
            }

            return View();
        }

        [HttpPost]
        public ActionResult Alterar(Produto produtoAlterado)
        {
            SetCategoriesViewBag();

            if (ModelState.IsValid)
            {
                using(var transaction = new Entities().Database.BeginTransaction())
                {
                    try
                    {
                        UnitOfWork.ProdutoDal.Atualizar(produtoAlterado);
                        UnitOfWork.CategoriaDal.Salvar();

                        transaction.Commit();
                    }
                    catch (DbEntityValidationException ex)
                    {
                        transaction.Rollback();
                        throw;
                    }
                    catch (Exception)
                    {
                        transaction.Rollback();
                        throw;
                    }
                }

                return RedirectToAction("Index");
            }

            return View(produtoAlterado);
        }

        public ActionResult Excluir(int id)
        {
            Produto produtoBanco = UnitOfWork.ProdutoDal.Obter(x => x.Id == id).FirstOrDefault();

            if(produtoBanco != null)
            {
                ViewBag.Categoria = UnitOfWork.CategoriaDal.Obter(x => x.Id == produtoBanco.CategoriaId).FirstOrDefault().Descricao;

                return View(produtoBanco);
            }

            return View();
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult ExcluirProduto(int id)
        {
            using(var transaction = new Entities().Database.BeginTransaction())
            {
                try
                {
                    int idCategoria = UnitOfWork.ProdutoDal.Obter(x => x.Id == id).FirstOrDefault().CategoriaId;
                    ViewBag.Categoria = UnitOfWork.CategoriaDal.Obter(x => x.Id == idCategoria).FirstOrDefault().Descricao;

                    UnitOfWork.ProdutoDal.Excluir(x => x.Id == id);
                    UnitOfWork.ProdutoDal.Salvar();

                    transaction.Commit();
                }
                catch (DbEntityValidationException ex)
                {
                    transaction.Rollback();
                    throw;
                }
                catch (Exception)
                {
                    transaction.Rollback();
                    throw;
                }
            }
            
            return RedirectToAction("Index");
        }

    }
}

CRUD/Views/Categoria/Alterar.cshtml
@model CRUD.Model.Categoria

@{
    ViewBag.Title = "Alterar";
}

<div class="row form-group">
    <div class="col-md-4">
        @using (Html.BeginForm("Alterar", "Categoria", FormMethod.Post))
        {
            <div class="form-group">
                <label for="email">Description:</label>
                @Html.TextBoxFor(x => x.Descricao, new { Class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", "Categoria", null, new { Class = "btn btn-danger" })
        }
    </div>
</div>

CRUD/Views/Categoria/Excluir.cshtml
@model CRUD.Model.Categoria

@{
    ViewBag.Title = "Excluir";
}

<div class="row form-group">
    <div class="col-md-4">
        @using (Html.BeginForm("Excluir", "Categoria", FormMethod.Post))
        {
            <div class="form-group">
                <label for="email">Description:</label>
                @Html.TextBoxFor(x => x.Descricao, new { Class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", "Categoria", null, new { Class = "btn btn-danger" })
        }
    </div>
</div>

CRUD/Views/Categoria/Index.cshtml
@model CRUD.Model.Categoria

@{
    ViewBag.Title = "Index";

    var categorias = ViewBag.Categorias as List<CRUD.Model.Categoria>;
}

<div class="row form-group">
    <div class="col-md-4">
        @using (Html.BeginForm("Index", "Categoria", FormMethod.Post))
        {
            <div class="form-group">
                <label for="email">Description:</label>
                @Html.TextBoxFor(x => x.Descricao, new { Class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Salvar</button>
        }
    </div>
</div>

@if (categorias != null && categorias.Count > 0)
{
<div class="row">
    <div class="col-md-4">
        <table class="table table-hover table-bordered">
            <tr>
                <th>Descrição</th>
            </tr>
            @foreach (var item in categorias)
            {
                <tr>
                    <td>@item.Descricao</td>
                    <td>
                        @Html.ActionLink("Alterar","Alterar", "Categoria", new { @id = item.Id },null)
                        @Html.ActionLink("Excluir", "Excluir", "Categoria", new { @id = item.Id }, null)
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
}

CRUD/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CRUD/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CRUD/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CRUD/Views/Produto/Alterar.cshtml
@model CRUD.Model.Produto

@{
    ViewBag.Title = "Alterar";
}

<div class="row form-group">
    <div class="col-md-4">
        @using (Html.BeginForm("Alterar", "Produto", FormMethod.Post))
        {
            <div class="form-group">
                <label>Description</label>
                @Html.TextBoxFor(x => x.Descricao, new { Class = "form-control" })
            </div>
            <div class="form-group">
                <label>Category</label>
                @Html.DropDownListFor(x => x.CategoriaId, (IEnumerable<SelectListItem>)ViewBag.Categorias, new { Class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", "Produto", null, new { Class = "btn btn-danger" })
        }
    </div>
</div>

CRUD/Views/Produto/Excluir.cshtml
@model CRUD.Model.Produto

@{
    ViewBag.Title = "Excluir";
}

<div class="row form-group">
    <div class="col-md-4">
        @using (Html.BeginForm("Excluir", "Produto", FormMethod.Post))
        {
            <div class="form-group">
                <label>Description</label>
                @Html.TextBoxFor(x => x.Descricao, new { Class = "form-control", Disabled = true })
            </div>
            <div class="form-group">
                <label>Category</label>

                <select class="form-control" disabled>
                    <option value="">@ViewBag.Categoria</option>
                </select>
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
            @Html.ActionLink("Cancel", "Index", "Produto", null, new { Class = "btn btn-danger" })
        }
    </div>
</div>

CRUD/Views/Produto/Index.cshtml
@model CRUD.Model.Produto

@{
    ViewBag.Title = "Index";

    var produtos = ViewBag.Produtos as List<CRUD.Model.Produto>;
}

<div class="row form-group">
    <div class="col-md-4">
        @using (Html.BeginForm("Index", "Produto", FormMethod.Post))
        {
            <div class="form-group">
                <label>Description</label>
                @Html.TextBoxFor(x => x.Descricao, new { Class = "form-control" })
            </div>
            <div class="form-group">
                <label>Category</label>
                @Html.DropDownListFor(x => x.CategoriaId, (IEnumerable<SelectListItem>)ViewBag.Categorias, "Selecione", new { Class = "form-control" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        }
    </div>
</div>

@if(produtos != null && produtos.Count > 0)
{
    <div class="row form-group">
        <div class="col-md-4">
            <table class="table table-hover">
                <tr>
                    <th>Description</th>
                    <th>Category</th>
                    <th></th>
                </tr>
                @foreach (var item in produtos)
                {
                    <tr>
                        <td>@item.Descricao</td>
                        <td>@item.Categoria.Descricao</td>
                        <td>
                            @Html.ActionLink("Alterar", "Alterar", "Produto", new { @id = item.Id }, null)
                            @Html.ActionLink("Excluir", "Excluir", "Produto", new { @id = item.Id }, null)
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
}

CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Categoria")</li>
                    <li>@Html.ActionLink("Products", "Index", "Produto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>